name: Build Artifacts

on:
  workflow_dispatch: 
  push:
    branches: [ master, build-test ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set jadx version
        run: |
          JADX_REV=$(git rev-list --count HEAD)
          JADX_VERSION="r${JADX_REV}.${GITHUB_SHA:0:7}"
          echo "JADX_VERSION=$JADX_VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Android App Debug
        run: ./gradlew :jadx-android-app:build

      - name: Build Android App Release
        run: ./gradlew :jadx-android-app:assembleRelease

      - name: Save Android Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-{0}-debug.apk', env.JADX_VERSION) }}
          path: jadx-android-app/build/outputs/apk/debug/jadx-android-app-debug.apk
          if-no-files-found: ignore
          retention-days: 14

      - name: Save Android Release APK
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-{0}-release.apk', env.JADX_VERSION) }}
          path: jadx-android-app/build/outputs/apk/release/jadx-android-app-release-unsigned.apk
          if-no-files-found: ignore
          retention-days: 14

      - name: Save Android Bundle
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('jadx-{0}.aab', env.JADX_VERSION) }}
          path: jadx-android-app/build/outputs/bundle/release/jadx-android-app-release.aab
          if-no-files-found: ignore
          retention-days: 14
